# Generated by Django 2.2.10 on 2020-10-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0002_auto_20201016_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorymapsChapter',
            new_name='Chapter',
        ),
        migrations.RenameModel(
            old_name='StorymapsGeoJsonOverlay',
            new_name='GeoJsonOverlay',
        ),
        migrations.RenameModel(
            old_name='StorymapsMarker',
            new_name='Marker',
        ),
        migrations.RenameModel(
            old_name='StorymapsStory',
            new_name='Story',
        ),
    ]
