# Generated by Django 2.2.10 on 2020-10-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0003_auto_20201016_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='geojson_overlay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='i_rorelse.GeoJsonOverlay'),
        ),
    ]
