# Generated by Django 2.2.10 on 2020-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0004_auto_20201016_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='zoom',
            field=models.IntegerField(blank=True, help_text='Only used in combination with a SINGLE marker, not with multiple markers or GEOJson-overlay.', null=True, verbose_name='Zoom'),
        ),
    ]
