# Generated by Django 2.2.10 on 2020-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0005_auto_20201016_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='overlay_transparency',
            field=models.FloatField(blank=True, help_text='Optional. Value between 0 and 1. E.g. 0.5', null=True, verbose_name='Overlay'),
        ),
    ]
