# Generated by Django 2.2.10 on 2020-10-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0007_auto_20201026_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='geojson_feature_properties',
            field=models.CharField(blank=True, help_text="e.g. 'weight:5; fillColor:orange'", max_length=255, null=True, verbose_name='GeoJSON Feature Properties'),
        ),
    ]
