# Generated by Django 2.2.10 on 2020-10-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0008_chapter_geojson_feature_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='i_rorelse.Chapter'),
            preserve_default=False,
        ),
    ]
