# Generated by Django 2.2.10 on 2020-10-27 09:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0009_auto_20201026_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description'),
        ),
    ]
