# Generated by Django 2.2.10 on 2020-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0010_auto_20201027_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='geojson_overlay',
            field=models.CharField(blank=True, help_text='comma separated list of country names and/or codes, e.g. <i>SE,Syria</i>', max_length=255, null=True, verbose_name='GeoJSON Overlay'),
        ),
        migrations.DeleteModel(
            name='GeoJsonOverlay',
        ),
    ]
