# Generated by Django 2.2.10 on 2020-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0011_auto_20201028_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
