# Generated by Django 2.2.10 on 2020-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_rorelse', '0012_auto_20201028_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
